apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: test
spec:
  template:
    spec:
      containers:
      - name: pi
        image: python:3.6-alpine
        command: ["python",  "-c", "print('HelloWorld')"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi2
  namespace: test
spec:
  template:
    spec:
      containers:
      - name: pi
        image: python:3.6-alpine
        command: ["python",  "-c", "print('HelloWorld')"]
      restartPolicy: Never