apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
  namespace: tower
  labels:
    app: tower
data:
  default.conf: |
    server {
        listen      80;
        charset     utf-8;
        client_max_body_size 75M;   # adjust to taste
        location /static {
            alias /usr/share/nginx/html/Tower/static; # your Django project's static files - amend as required
        }
        location / {
            include     uwsgi_params; # the uwsgi_params file you installed
            uwsgi_pass  tower-backend:8000;
        }
    }
