apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tower-nginx
  namespace: tower
spec:
  selector:
    matchLabels:
      app: tower-nginx
  template:
    metadata:
      labels:
        app: tower-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.6
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/Tower
          name: web-volume
        - mountPath: /etc/nginx/conf.d/
          name: conf
      volumes:
      - name: web-volume
        hostPath:
          path: /Tower/Tower
          type: Directory
      - name: conf
        configMap:
          name: conf