apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tower-backend
  namespace: tower
spec:
  selector:
    matchLabels:
      app: tower-backend
  serviceName: tower-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: tower-backend
    spec:
      containers:
      - name: tower
        image: django:backend
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /usr/share/nginx/html/Tower
          name: web-volume
      volumes:
      - name: web-volume
        hostPath:
          path: /Tower/Tower
          type: Directory
      - name: conf
        configMap:
          name: conf